# bootstrap-structure.ps1
# Script 1: Folder structure bootstrapper for issueSmith

# Create subfolders
$folders = @("assets", "docs", "tests", "archive")
foreach ($f in $folders) {
    New-Item -ItemType Directory -Force -Path ".\$f" | Out-Null
}

# Add placeholder README.txt files to keep structure
$placeholderText = "Placeholder file to keep folder structure."
Set-Content -Path ".\assets\README.txt" -Value $placeholderText
Set-Content -Path ".\docs\README.txt"   -Value $placeholderText
Set-Content -Path ".\tests\README.txt"  -Value $placeholderText
# archive intentionally left empty

# Root files
New-Item -ItemType File -Force -Path ".\.gitignore" | Out-Null
New-Item -ItemType File -Force -Path ".\index.html" | Out-Null

# Root README.md with explanation of Script 1
$readme = @"
# issueSmith – Bootstrap Scaffold

This project folder was generated by **Script 1: Folder structure bootstrapper**.

### What this script did:
- Created subfolders:
  - `assets/` (with README.txt placeholder)
  - `docs/` (with README.txt placeholder)
  - `tests/` (with README.txt placeholder)
  - `archive/` (empty, ignored in Git)
- Created root files:
  - `.gitignore` (empty, to configure later)
  - `index.html` (empty shell, to populate later)
  - `README.md` (this file, describing Script 1 actions)

### Next Step:
Run Script 2 to populate these files with initial content and Git setup.
"@
Set-Content -Path ".\README.md" -Value $readme

Write-Host "✅ issueSmith folder structure created successfully."
